# Default values for skupper-site-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

customhostname: false "use when a custom route is required for skupper-inter-router"
ingress:
  enabled: true
  host: skupper-inter-router-custom
  domain: test.com 
  #exmaple: if customhostname is enabled, interrouter route url will be skupper-inter-router-custom.test.com


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

vault:
  image:
  repository: vault
  pullPolicy: IfNotPresent
  tag: "latest"

skupper:
  router:
    image:
      repository: quay.io/skupper/skupper-router
      pullPolicy: IfNotPresent
      tag: "2.1.0"
    resources: 
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    replicaCount: 1
  configsync:
    image:
      repository: quay.io/skupper/config-sync
      pullPolicy: IfNotPresent
      tag: "1.1.1"   
    resources: 
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  servicecontroller:
    image:
      repository: quay.io/skupper/service-controller
      pullPolicy: IfNotPresent
      tag: "1.1.1" 
    resources: 
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    replicaCount: 1
  sitecontroller:
    image:
      repository: quay.io/skupper/site-controller
      pullPolicy: IfNotPresent
      tag: "1.1.1" 
    resources: 
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    replicaCount: 1

#if you have other sites to connect to, add them here in a list, name will be the namepsace of the other site and host will be the skupper interrouter url of other site
remoteSites:
   - name: namespace1
     host: skupper-inter-router-test.dev

