apiVersion: v1
kind: Service
metadata:
  name: skupper
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: claims
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: skupper-service-controller
    app.kubernetes.io/part-of: skupper
    skupper.io/component: service-controller
  sessionAffinity: None
  type: ClusterIP
