apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-skupper-site-controller
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: skupper
      app.kubernetes.io/name: skupper-site-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: skupper
        app.kubernetes.io/name: skupper-site-controller
        app.kubernetes.io/part-of: skupper
        application: skupper-site-controller
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: QDROUTERD_IMAGE
          value: {{ .Values.skupper.router.image.repository }}:{{ .Values.skupper.router.image.tag }}
        - name: SKUPPER_SERVICE_CONTROLLER_IMAGE
          value: {{ .Values.skupper.servicecontroller.image.repository }}:{{ .Values.skupper.servicecontroller.image.tag }}
        - name: SKUPPER_CONFIG_SYNC_IMAGE
          value: {{ .Values.skupper.configsync.image.repository }}:{{ .Values.skupper.configsync.image.tag }}
        image: {{ .Values.skupper.siteController.image.repository }}:{{ .Values.skupper.siteController.image.tag }}
        imagePullPolicy: IfNotPresent
        name: skupper-site-controller
        resources:
{{ toYaml .Values.skupper.siteController.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: skupper-site-controller
      serviceAccountName: skupper-site-controller
      terminationGracePeriodSeconds: 30